# Generated by Django 4.2.2 on 2023-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=250)),
                ("key", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("modified", "Modified"),
                            ("deleted", "Deleted"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
